### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by leeper** [lbraglia/PackageDevelopmentTaskView#4]
This seemed really useful, but it maybe you're not working on it any more.

**Comment by lbraglia** [comment]
Hi Thomas, 

the short version is No (i'm not working on it). Here's the long one

https://stat.ethz.ch/pipermail/r-devel/2015-January/070485.html

After a few time, one guy volounteered to maintain/develop

https://stat.ethz.ch/pipermail/r-devel/2015-January/070500.html

but since then, i've heard him no more. 

So, if you're interested in leading this CTV, it's perfectly ok for me.

best, Luca

**Comment by leeper** [comment]
Okay, I've forked. I'm not sure I have time to maintain it either, but I'll
put some thought on it and see if I can recruit any other volunteers to
help out.
